apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-kustomize-app-dev
  namespace: argocd
dependencies:
  - name: quarkus
  version: 0.0.3
  repository: https://redhat-developer.github.io/redhat-helm-charts
spec:
  project: default
  source:
    repoURL: https://github.com/MuKuLJain07/kustomize-argo.git
    targetRevision: HEAD
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-kustomize-app-prod
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-status-change.slack: "#dotpe-non-prod-alerts"
spec:
  project: default
  source:
    repoURL: https://github.com/MuKuLJain07/kustomize-argo.git
    targetRevision: HEAD
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

T