# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: cluster-autoscaler
#   namespace: kube-system
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: cluster-autoscaler
#   template:
#     metadata:
#       labels:
#         app: cluster-autoscaler
#     spec:
#       containers:
#       - name: cluster-autoscaler
#         image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.22.2
#         command:
#         - ./cluster-autoscaler
#         - --v=4
#         - --stderrthreshold=info
#         - --cloud-provider=aws
#         - --nodes=1:10:your-node-group-name

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
spec:
  selector:
    matchLabels:
      app: cluster-autoscaler
  replicas: 1
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      containers:
      - image: bitnami/cluster-autoscaler
        name: cluster-autoscaler
        command:
        - /cluster-autoscaler
        args:
        - --cloud-provider=clusterapi
      serviceAccountName: cluster-autoscaler
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane