apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- default-services/


namePrefix: myapp-

images:
- name: nginx
  newTag: latest
labels:
- includeSelectors: true
  pairs:
    app: my-app
